"""Memoire associative, pipeline durable et laboratoires locaux bornes.

Les composants publics restent separables afin qu'un agent puisse calculer
sans ecrire dans la memoire, ou utiliser la memoire sans calculateur.
"""

from .memory import MemoryEngine, MemoryIdempotencyConflictError
from .math_engine import MathEngine, MathEngineError
from .mat9f import (
    FUNCTION_ORDER,
    FunctionContext,
    MAT9FError,
    NeuronResult,
    NineFunctionBlock,
    PropagationResult,
    RecursiveNineFunctionEngine,
    SignalPacket,
)
from .mat9f_zero import (
    ExponentialZeroMesh,
    GATE_FUNCTIONS,
    ZeroAlgorithm,
    ZeroDispatchResult,
    ZeroDrop,
    ZeroExecutionResult,
    ZeroGateAddress,
    ZeroHop,
    ZeroHubAddress,
)
from .mat9f_zero_adaptive import (
    AdaptiveGateTrace,
    AdaptiveTerminal,
    AdaptiveZeroEngine,
    AdaptiveZeroNetwork,
    AdaptiveZeroPolicy,
    AdaptiveZeroResult,
    TransitionDecision,
    ZeroTransition,
)
from .mat9f_zero_conversation import (
    attest_external_evidence,
    ConversationConfirmation,
    ConversationEvidence,
    ConversationTurn,
    DeterministicZeroConversationAdapter,
    ZeroConversationDecision,
    ZeroConversationPreparation,
)
from .mat9f_cortex_cylinder import (
    CortexCenterAddress,
    CortexCylinder,
    CortexDisk,
    CortexDiskAddress,
    CortexDiskProfile,
    CortexDispatchResult,
    CortexExecutionResult,
    CortexGateAddress,
    CortexGateSpec,
    CortexHop,
    CortexLink,
    CortexLinkKind,
    CortexRoute,
    CortexRoutingPolicy,
    SignedCortexDiskProfile,
    reference_cylinder,
    reference_profiles,
)
from .matlm_conversation import (
    ConversationAccessError,
    ConversationConflictError,
    ConversationContext,
    ConversationError,
    ConversationLimitError,
    ConversationSnapshot,
    ConversationTurn as MATLMConversationTurn,
    LocalConversationStore,
)
from .memory_hub import (
    GeneratedObservationError,
    MemoryAccessError,
    MemoryHub,
    SpacePolicy,
)
from .history_stress_lab import (
    HistoryStressConfig,
    generate_history_scenario,
    history_stress_catalog,
    run_history_stress,
)
from .pipeline import (
    BackgroundConsolidator,
    DurableInjectionQueue,
    IdempotencyConflictError,
    MemoryPipeline,
    QueueStateError,
)
from .science_curriculum import (
    ScienceCurriculumError,
    build_science_capsules,
    import_science_reference,
    load_science_dataset,
)

__all__ = [
    "AdaptiveGateTrace",
    "AdaptiveTerminal",
    "AdaptiveZeroEngine",
    "AdaptiveZeroNetwork",
    "AdaptiveZeroPolicy",
    "AdaptiveZeroResult",
    "BackgroundConsolidator",
    "ConversationConfirmation",
    "ConversationAccessError",
    "ConversationConflictError",
    "ConversationContext",
    "ConversationError",
    "ConversationEvidence",
    "ConversationLimitError",
    "ConversationSnapshot",
    "ConversationTurn",
    "CortexCenterAddress",
    "CortexCylinder",
    "CortexDisk",
    "CortexDiskAddress",
    "CortexDiskProfile",
    "CortexDispatchResult",
    "CortexExecutionResult",
    "CortexGateAddress",
    "CortexGateSpec",
    "CortexHop",
    "CortexLink",
    "CortexLinkKind",
    "CortexRoute",
    "CortexRoutingPolicy",
    "DeterministicZeroConversationAdapter",
    "DurableInjectionQueue",
    "IdempotencyConflictError",
    "HistoryStressConfig",
    "FUNCTION_ORDER",
    "GATE_FUNCTIONS",
    "FunctionContext",
    "ExponentialZeroMesh",
    "MathEngine",
    "MathEngineError",
    "MAT9FError",
    "GeneratedObservationError",
    "MemoryAccessError",
    "MemoryEngine",
    "MemoryHub",
    "MemoryIdempotencyConflictError",
    "MemoryPipeline",
    "MATLMConversationTurn",
    "NeuronResult",
    "NineFunctionBlock",
    "PropagationResult",
    "QueueStateError",
    "RecursiveNineFunctionEngine",
    "ScienceCurriculumError",
    "SpacePolicy",
    "SignalPacket",
    "SignedCortexDiskProfile",
    "TransitionDecision",
    "ZeroAlgorithm",
    "ZeroDispatchResult",
    "ZeroDrop",
    "ZeroExecutionResult",
    "ZeroGateAddress",
    "ZeroHop",
    "ZeroHubAddress",
    "ZeroTransition",
    "ZeroConversationDecision",
    "ZeroConversationPreparation",
    "build_science_capsules",
    "attest_external_evidence",
    "generate_history_scenario",
    "history_stress_catalog",
    "import_science_reference",
    "load_science_dataset",
    "LocalConversationStore",
    "reference_cylinder",
    "reference_profiles",
    "run_history_stress",
]
__version__ = "0.6.0"
